### ISSUE TITLE
MapReduce & Hadoop

### ISSUE THREAD

**Issue by Sameh-Manaa** [Sameh-Manaa/BD2017#1]

**Comment by HorizonNet** [comment]
Below is a short review.

**Tasks**

- [x]  Download a book text from the Gutenberg Project and copy it into HDFS
- [x] Write a MapReduce program that does a WordCount on an arbitrary text file
- [x] Package your WordCount application into a Maven project and build it
- [x] Using `teragen` and `terasort`

Below are a few comments/suggestions:

* Please use correct Markdown formatting for code snippets (see `hdfs-test.md`).
* There's no need to pipe the results of the HDFS tests into files.
* For upcoming tasks, also provide the full output of a command.
* There is no need for class fields in your `WordCount` application. They would better be method local variables.

Open points:

* You didn't package the WordCount application. Also, the Maven project does not work at all. Run `mvn clean install` in the Maven-root directory to make sure that everything works.

Summary:

You're done with this one. Good work.

**Comment by Sameh-Manaa** [comment]
* ``` hdfs-test.md ``` has been modified according to the Markdown formatting
* Built the WordCount maven project using the ``` mvn clean install ```

**Comment by HorizonNet** [comment]
Building the Maven project still does not work. Under any circumstances, you should not use

    <scope>system</scope>
    <systemPath>${basedir}\src\libs\hadoop-common-2.8.0.jar</systemPath>

With that you tell maven to look into your local directory and destroys any advantages you will get with Maven (e.g. automatic dependency download). Also, sharing your code with others will become terrible, because they need to have the same JARs at the exact same location.

**Comment by Sameh-Manaa** [comment]
I think I have figured out the problem with my maven project
* First: I have used a wrong groupId for the hadoop JARs ==> corrected (groupId: org.apache.hadoop)
* Second: As you mentioned, I was loading the libraries from my local drive ==> corrected (Removed)

Please advise if those were the real problems
I have repackaged the project and installed it and it should work fine now.

Thanks

**Comment by HorizonNet** [comment]
Yes, these were the two problems. I updated my review comment above. As an advice, don't commit files directly in GitHub. Make your changes locally and then push them to GitHub. That ensures that you always have a local copy of your repository.
